service: aseekbot-api

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    AWS_S3_BUCKET_NAME: ${env:AWS_S3_BUCKET_NAME}
    DOCUMENT_ANALYSIS_STATE_MACHINE_ARN: ${env:DOCUMENT_ANALYSIS_STATE_MACHINE_ARN, 'arn:aws:states:us-east-1:361769603480:stateMachine:DocumentAnalysisWorkflow'}
    DOCUMENT_ANALYSIS_STATUS_TABLE: ${env:DOCUMENT_ANALYSIS_STATUS_TABLE, 'DocumentAnalysisStatus'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
        - s3:DeleteObject
      Resource: "arn:aws:s3:::${env:AWS_S3_BUCKET_NAME}/*"
    - Effect: Allow
      Action:
        - bedrock:*
      Resource: "*"
    - Effect: Allow
      Action:
        - states:StartExecution
        - states:DescribeExecution
      Resource: "*"
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:Query
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/DocumentAnalysisStatus"
    # Add the following permissions for Textract
    - Effect: Allow
      Action:
        - textract:StartDocumentTextDetection
        - textract:GetDocumentTextDetection
        - textract:DetectDocumentText
        - textract:AnalyzeDocument
      Resource: "*"

functions:
  processChatMessage:
    handler: lambdas/processChatMessage.handler
    events:
      - http:
          path: processChatMessage
          method: post
          cors: true # Enable CORS
  uploadFile:
    handler: lambdas/uploadFile.handler
    events:
      - http:
          path: uploadFile
          method: post
          cors: true # Enable CORS
  deleteFile:
    handler: lambdas/deleteFile.handler
    events:
      - http:
          path: deleteFile
          method: post
          cors: true # Enable CORS
  createTicket:
    handler: lambdas/createTicket.handler
    events:
      - http:
          path: createTicket
          method: post
          cors: true # Enable CORS
  quickLink:
    handler: lambdas/quickLink.handler
    events:
      - http:
          path: quickLink
          method: post
          cors: true # Enable CORS
  processMessage:
    handler: lambdas/processMessage.handler
    events:
      - http:
          path: processMessage
          method: post
          cors: true # Enable CORS
  documentAnalysis:
    handler: lambdas/getDocumentAnalysisStatus.handler
    events:
      - http:
          path: document-analysis/{proxy+}
          method: any
          cors: true # Enable CORS
  initProcess:
    handler: functions/document-analysis/init-process.handler
    name: aseekbot-api-dev-init-process
  fileValidation:
    handler: functions/document-analysis/file-validation.handler
    name: aseekbot-api-dev-file-validation
  textractPdf:
    handler: functions/document-analysis/textract-pdf.handler
    name: aseekbot-api-dev-textract-pdf
  docxParser:
    handler: functions/document-analysis/docx-parser.handler
    name: aseekbot-api-dev-docx-parser
  excelParser:
    handler: functions/document-analysis/excel-parser.handler
    name: aseekbot-api-dev-excel-parser
  csvParser:
    handler: functions/document-analysis/csv-parser.handler
    name: aseekbot-api-dev-csv-parser
  contentAnalyzer:
    handler: functions/document-analysis/content-analyzer.handler
    name: aseekbot-api-dev-content-analyzer
  documentComparer:
    handler: functions/document-analysis/document-comparer.handler
    name: aseekbot-api-dev-document-comparer
  insightGenerator:
    handler: functions/document-analysis/insight-generator.handler
    name: aseekbot-api-dev-insight-generator
  resultStorage:
    handler: functions/document-analysis/result-storage.handler
    name: aseekbot-api-dev-result-storage
  errorHandler:
    handler: functions/document-analysis/error-handler.handler
    name: aseekbot-api-dev-error-handler
  statusUpdater:
    handler: functions/document-analysis/status-updater.handler
    name: aseekbot-api-dev-status-updater

# Add custom section for more detailed CORS configuration
custom:
  cors:
    allowOrigin: '*'
    allowHeaders:
      - Content-Type
      - X-Amz-Date
      - Authorization
      - X-Api-Key
      - X-Amz-Security-Token
      - X-Amz-User-Agent
    allowMethods:
      - OPTIONS
      - POST
      - GET
